import * as authSchema from "./auth.schema"; // Generated by Better Auth CLI

// Export all schemas for migrations
// NeoDB schemas are now managed by Better Auth plugin system
export const schema = {
    ...authSchema,
} as const;
